imports:
    - { resource: 'services.yaml' }

services:
    Ssch\TYPO3Rector\Rector\Core\Utility\MoveApplicationContextToEnvironmentApiRector: ~
    Ssch\TYPO3Rector\Rector\Core\ExcludeServiceKeysToArrayRector: ~
