services:
  Ssch\TYPO3Rector\Annotation\InjectAnnotation: ~
  Ssch\TYPO3Rector\Annotation\CascadeAnnotation: ~
  Ssch\TYPO3Rector\Annotation\IgnoreValidationAnnotation: ~
  Ssch\TYPO3Rector\Annotation\LazyAnnotation: ~
  Ssch\TYPO3Rector\Annotation\TransientAnnotation: ~
  Ssch\TYPO3Rector\Annotation\ValidateAnnotation: ~
  Ssch\TYPO3Rector\Core\Environment\ConstantToEnvironmentCallRector: ~
  Ssch\TYPO3Rector\Core\Environment\RenameMethodCallToEnvironmentMethodCallRector: ~
