imports:
    - { resource: 'services.yaml' }

services:
    Ssch\TYPO3Rector\Rector\Core\CheckForExtensionInfoRector:
    Ssch\TYPO3Rector\Rector\Core\Utility\RefactorMethodsFromExtensionManagementUtilityRector:
    Ssch\TYPO3Rector\Rector\SysNote\Domain\Repository\FindByPidsAndAuthorIdRector:
