imports:
    - { resource: 'services.yaml' }

services:
    Ssch\TYPO3Rector\Rector\Extbase\RemovePropertyExtensionNameRector: ~
    Ssch\TYPO3Rector\Rector\Extbase\Utility\UseNativePhpHex2binMethodRector: ~
    #Ssch\TYPO3Rector\Rector\Migrations\RenameClassMapAliasRector:
    #    $classAliasMaps:
    #        - '../../../Migrations/Core/v10/ClassAliasMap.php'
