imports:
    - { resource: "%vendor_dir%/../config/services.yaml" }

services:
    Rector\Renaming\Rector\MethodCall\RenameMethodCallRector:
        TYPO3\CMS\Backend\Controller\Page\LocalizationController:
            getUsedLanguagesInPageAndColumn: getUsedLanguagesInPage
