imports:
    - { resource: 'services.yaml' }

services:
    Ssch\TYPO3Rector\Rector\Extbase\RemovePropertyExtensionNameRector: ~
    Ssch\TYPO3Rector\Rector\Extbase\Utility\UseNativePhpHex2binMethodRector: ~
    Ssch\TYPO3Rector\Rector\Core\Utility\RefactorIdnaEncodeMethodToNativeFunctionRector: ~
    #Ssch\TYPO3Rector\Rector\Migrations\RenameClassMapAliasRector:
    #    $classAliasMaps:
    #        - '../../../Migrations/Core/v10/ClassAliasMap.php'
    Rector\Renaming\Rector\Namespace_\RenameNamespaceRector:
        $oldToNewNamespaces:
            TYPO3\CMS\Backend\Controller\File: TYPO3\CMS\Filelist\Controller\File
    Ssch\TYPO3Rector\Rector\Core\Resource\UseMetaDataAspectRector: ~
