parameters:
    autoload_paths:
        - 'config/Migrations/Code/LegacyClassesForIde.php'

services:
    Ssch\TYPO3Rector\Rector\Migrations\UnderscoreToNamespaceRector:
        'oldClassAliasMap': 'config/Migrations/Code/ClassAliasMap.php'


