name: Format (PHP)

on:
    pull_request:
        paths:
            - '**.php'

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   uses: shivammathur/setup-php@v1
                    with:
                        php-version: 7.2
                        coverage: none

            -   run: composer install --no-progress

            -   name: Run php-cs-fixer
                run: ./vendor/bin/php-cs-fixer fix --config=./.php_cs.dist

            -   uses: stefanzweifel/git-auto-commit-action@v2.1.0
                with:
                    commit_message: Apply php-cs-fixer changes
                    branch: ${{ github.head_ref }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
