name: PHP Composer

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: shivammathur/setup-php@v1
      with:
        php-version: 7.2
        coverage: none # disable xdebug, pcov
        extensions: "intl"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script test
